config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resource :profile
    resources :posts
  end
  

  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    root 'dashboard#index'
  end
  
  get 'home/index'

  root 'home#index'
  match '/signup', to: 'users#new',         via: 'get'
  match '/signin', to: 'sessions#new',      via: 'get'
  match '/signout', to: 'sessions#destroy',  via: 'delete'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase}
  before_create :create_remember_token
 
  #Associations
  has_one :profile
  has_many :posts

  #validations
  validates :name, presence: true, length:  {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format:  {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  
  has_secure_password
  validates :password, length: {minimum: 6}
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private 
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin'

  def index
    @time = Time.now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
=begin
  def authorize
    if current_user.nil?
      flash[:danger] = "Not authorized"
      redirect_to signin_url
    end 
    #redirect_to signin_url, danger: "Not authorized" if current_user.nil?
  end
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
=end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
=begin   
   if current_user
      redirect_to user_path(current_user.id)
    end
=end
    @time = Time.now
    @posts= Post.all
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  #before_action :find_profile, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user
 
  def show
    @user = User.find(params[:user_id])
    @profile = @user.profile
  end

  def new
     
  end

  def create
    @user = User.find(parmas[:id])
    @profile = @user.profile.create(profile_parmas)
    redirect user_path(@user)
  end

  def edit
  end
 
  def update
  end

  def destroy
  end

  private
  def profile_params
    params.require(:profile).permit(:description)
  end
  
  def find_profile
    @profile = Profile.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
    sign_in user
    #session[:user_id] = user.id
    flash[:success] = "Welcome in Social Network 2014 #{user.name}"
    redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    flash[:info] = 'Logged out'
    redirect_to root_url
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
 # before_action :authorize, only: [:show] 
  
 # before_action :signed_in_user, only: [:show]
 # before_action :correct_user,   only: [:create, :new]
  

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver
      sign_in @user
      flash[:success] = "Welcome in Social Network 2014! #{@user.name}"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Ruby on Rails Social Network 2014"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end  

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end


  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def current_user?(user)
    user == current_user
  end 

  def signed_in_user
    unless signed_in?
      flash[:danger] ="Please sign in"
      redirect_to signin_url
    end
    #redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end
 
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/admin/dashboard/index.html.erb
<h1>DASHBOARD SOCIAL NETWORK 2014</h1>
<p class="center"><%= @time%></p>

app/views/admin/shared/_header.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/admin/shared/_top_menu.html.erb
<div class="navbar  navbar-default" role="navigation">
  <div class="container">
    <div class= "navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> 
      <%= link_to "DASHBOARD SOCIAL NETWORK 2014", admin_root_path, :class=> "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="form">
        <div class="form-group">
           <input type="text" placeholder="Email" class="form-control">
        </div> 
        <div class="form-group">
           <input type="text" placeholder="Password" class="form-control">
        </div> 
        <button type="submit" class="btn btn-primary">Sign in</button>
      </form>
    <!--
     <ul class="nav  navbar-nav pull-right">
      <li><#%= link_to "Home", root_path() %></li>  
      </ul>
    -->
    </div>
  </div>
</div>

app/views/home/_home_page.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
      <div class="row">
        <h1> SOCIAL NETWORK 2014</h1>
      </div>
      <hr>
      <div class="row">
        
        <div class="col-md-6">
          <p>
          Social Network 2014, si tratta di un'applicazione Ruby on Rails sviluppata durante il corso di sistemi informativi, presso l'Università degli Studi di Catania.
          Il corso è stato tenuto dal Prof. Alberto Faro.
          </p>
          <p>
            <%= link_to 'Sign Up', signup_path, class: 'btn btn-primary btn-lg btn-block'  %>
            <%= link_to 'Sign In', signin_path, class: 'btn btn-default btn-lg btn-block'  %>
          </p>
        </div>
      
        <div class="col-md-5 col-md-offset-1">
          <h4>CARATTERISITICHE TECNICHE DELL'APPLICAZIONE</h4>
          <ul>
            <li>RUBY ON RAILS 4.1.7</li>
            <li>RUBY 2.1.4</li>
            <li>"GEM BOOTSTRAP" PER IL LAYOUT</li>
            <li>"GEM BCRYPT" PER L'AUTENTICAZIONE</li>
            <li>REPOSITORY SU GITHUB <a href="https://github.com/AscWebApps/social_network">SOCIAL NETWORK 2014</a></li>
            <li><a href="http://www.antoninoscaffidi.it/courses/1-ruby-on-rails">DOCUMENTAZIONE</a></li>
          <ul>
        </div>

      </div>
         <hr>
         <p class="center"><%= @time.strftime("%d %b,%Y")%></p>
  </div>
</div>
</div>

app/views/home/index.html.erb
<%provide(:title, 'Home')%>
<%if signed_in?%>
  <div class="row">
    
    <div class="col-md-4">
      <%= gravatar_for current_user%>
      <hr>
      <!--
      <#%= link_to "Prifilo", user_profile_path(current_user.id, current_user.profile)%>
      -->
    </div>

    <div class="col-md-8">
      <% @posts.each do |post|%>
        <ul>
          <li><b><%= post.title%></b></li>
          <li><i><%= post.body%></i></li>
          <li><%=link_to post.user.name,user_path(post.user_id) %></li> 
        </ul>
        <hr>
      <%end%>
    </div>
    
  </div> 
<%else%>
  <%= render partial: "home_page"%>
<%end%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social Network</title>
  <%= render :partial =>"admin/shared/header"%>
</head>
<body>

<%= render :partial =>"/admin/shared/top_menu"%>

<div class="container">
  <%= yield %>
  <%= debug(params) if Rails.env.development?%>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%> </title>
  <%= render :partial =>"shared/header"%>
</head>
<body>

<%= render :partial =>"shared/top_menu"%>

<div class="container">
  
  <%flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %>
      <a class="close" data-dismiss="alert">&#215;</a>
    </div>
  <% end %> 
  
  <hr>
  <%= yield %>
  <hr>
      
<footer>
    <p>© Corso Sistemi Informativi 2013/2014 Università degli studi di Catania <%= Time.now.year%></p>
</footer>
  <%= debug(params) if Rails.env.development?%>
  
</div>
</body>
</html>

app/views/profiles/edit.html.erb
<h1>Profiles#edit</h1>
<p>Find me in app/views/profiles/edit.html.erb</p>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>

app/views/profiles/show.html.erb
<div class="row">
  <div class ="col-md-3">
      <%= render partial: "shared/sidebar_user"%> 
    <hr>
  </div>
  
  <div class="col-md-9">
    <div class="jumbotron">
      <h3>Profilo</h3>
      <small>Modifica le impostaioni di base del tuo account</small>
      <hr>
       <%= @profile.description%> 
    </div>
  </div>

</div>

app/views/shared/_error_messages.html.erb
<%if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <a class="close" data-dismiss="alert">&#215</a>
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/shared/_sidebar_user.html.erb
<%= gravatar_for @user%>
<hr>
<%= @user.name%>
<hr>
<%if current_user == @user%>
<div class="panel panel-default">
 <!-- <div class="panel-heading">
    <h4 class="panel-title text-center">PROFILE</h4>
  </div>
  -->
  <div class="list-group">
    <a href="<%= user_path(@user)%>" class="list-group-item">
      <p class="list-group-item-text">Account</p>
    </a>
    <a href="#" class="list-group-item">
      <p class="list-group-item-text">Password</p>
    </a>
    <a href="<%= user_profile_path(current_user)%>" class="list-group-item">
      <p class="list-group-item-text">Profile</p>
    </a>
  </div>
</div>
<%end%>

app/views/shared/_top_menu.html.erb
<div class="navbar  navbar-inverse" role="navigation">
  <div class="container">
    <div class= "navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> 
      <%= link_to "SOCIAL NETWORK", root_path, :class=> "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      
      <% if signed_in? %>
        
        <ul class="nav navbar-nav navbar-right">
          <li class ="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li> <%= link_to "Account", user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log Out", session_path("current"), method: "delete" %></li>
            </ul>
          <li>
        </ul>

      <% else %>
        <!--
        <#%if controller.controller_name=="sessions"%>
        <#%else%>
        <#%= form_for(:session, url: sessions_path, :html =>{class: "navbar-form navbar-right"}) do |f| %>
          <div class="form-group">
            <#%= f.text_field :email, class: "form-control", placeholder: "Email" %>
          </div>
          <div class="form-group">
            <#%= f.password_field :password, class: "form-control", placeholder: "Password" %>
          </div>
          <#%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
        <#% end %>
        <#%end%>
        -->
      <% end %>
    
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%provide(:title, "Sign up")%>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, :class=>"form-control", :placeholder =>"Name"%>
      </div>
   
      <div class="form-group">
        <%= f.label :email, "Email" %>
        <%= f.text_field :email, :class=>"form-control", :placeholder =>"Email"%>
      </div> 
      
      <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, :class=>"form-control", :placeholder =>"Password"%>
      </div>
        
      <div class="form-group">
        <%= f.label :password_confirmation,"Password Confirmation" %>
        <%= f.password_field :password_confirmation, class:"form-control", :placeholder =>"Password Confirmation"%>
      </div>
      <br>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name)%>
<div class="row">
  <div class ="col-md-3">

      <%= render partial: "shared/sidebar_user"%> 
    <hr>
  </div>
  
  <div class="col-md-9">
    <div class="jumbotron">
      <h3>Account</h3>
      <small>Modifica le impostaioni di base del tuo account</small>
      <hr>
        
    </div>
  </div>

</div>